
[font]
size = 12.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = false

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[window]
dynamic_title = true
opacity = 0.97

[general]

live_config_reload = true
import = [ "~/.config/alacritty/themes/catppuccin-macchiato.toml" ]
